Description: Building a EC2 instance with a Go application

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9
      InstanceType: t2.micro
      KeyName: KP-GEN
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          LOG_FILE="/var/log/userdata_execution.log"
          {
            # Defina o diretório de trabalho
            WORK_DIR="$HOME/cf-with-actions"

            # Atualize o sistema e instale pacotes
            sudo yum update -y
            sudo yum install -y golang git

            # Clone o repositório
            echo "Clonando o repositório..." &>> $LOG_FILE
            git clone https://github.com/vict0rcarvalh0/cf-with-actions.git $WORK_DIR &>> $LOG_FILE

            # Verifique se o diretório existe
            if [ ! -d "$WORK_DIR" ]; then
              echo "Erro: O repositório não foi clonado corretamente para $WORK_DIR." &>> $LOG_FILE
              exit 1
            fi

            echo "Listando conteúdo do diretório clonado:" &>> $LOG_FILE
            ls -l $WORK_DIR &>> $LOG_FILE

            # Mude para o diretório do projeto
            echo "Mudando para o diretório do projeto..." &>> $LOG_FILE
            cd $WORK_DIR/src/sample-app-go &>> $LOG_FILE

            # Verifique se o diretório existe
            if [ $? -ne 0 ]; then
              echo "Erro: O diretório do projeto não existe em $WORK_DIR/src/sample-app-go." &>> $LOG_FILE
              exit 1
            fi

            # Inicialize e execute a aplicação Go
            echo "Inicializando e executando a aplicação Go..." &>> $LOG_FILE
            export GOCACHE="$HOME/.cache/go-build"
            go mod init src/sample-app-go &>> $LOG_FILE
            go mod tidy &>> $LOG_FILE
            go build &>> $LOG_FILE
            ./src/sample-app-go &>> $LOG_FILE
          } 2>&1 | tee -a $LOG_FILE

  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [webapp-security-group, dev]]
      GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0