AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ReactAppBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: your-react-app-bucket-name
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:
  ReactAppBucketName:
    Description: "Name of the S3 bucket created for React app"
    Value: !Ref ReactAppBucket
