name: Node.js CI - Testing Act
'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: src/sample-frontend-react
        run: npm install

      - name: Build the React app
        working-directory: src/sample-frontend-react
        run: npm run build