name: Pipeline CD - DeployBuddies

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform -chdir=terraform/deploy-buddies/prod init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Apply
      id: apply
      run: terraform -chdir=terraform/deploy-buddies/prod apply -auto-approve

    - name: Get Terraform Outputs
      id: outputs
      run: terraform -chdir=terraform/deploy-buddies/prod output -json > outputs.json

    - name: Verify Private Key Creation
      run: |
        if [ ! -f "./terraform/deploy-buddies/prod/DEPLOYBUDDY-KP.pem" ]; then
          echo "Private key not found!"
          exit 1
        else
          echo "Private key created successfully."
        fi

    - name: Display EC2 Instance IDs
      run: |
        cat outputs.json
        instance_ids=$(jq -r '.backend_instance_ids.value[]' outputs.json)
        echo "Instance IDs: $instance_ids"

    - name: SSH into EC2 Instances
      run: |
        instance_ids=$(jq -r '.backend_instance_ids.value[]' outputs.json)
        for instance_id in $instance_ids; do
          public_ip=$(aws ec2 describe-instances --instance-ids $instance_id --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
          echo "Connecting to instance $instance_id with IP $public_ip"
          ssh -o StrictHostKeyChecking=no -i ./terraform/deploy-buddies/prod/DEPLOYBUDDY-KP.pem ec2-user@$public_ip 'echo "Hello from $(hostname)"'
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
