name: React CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Construir e rodar Docker
      run: |
        docker build -t frontend .
        docker run -d -p 80:80 frontend
