name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set Release Tag and Name
      id: set-release
      run: |
        DATE=$(date +'%Y-%m-%d')
        TAG="release-${DATE}-1"
        echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
        echo "RELEASE_NAME=Release $DATE" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: ${{ env.RELEASE_NAME }}
        draft: false
        prerelease: false
        body: "New release for ${{ env.RELEASE_NAME }}"